//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Reg_Auth.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public string User_Surname { get; set; }
        public string User_Name { get; set; }
        public string User_Patronymic { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<int> ID_Gender { get; set; }
        public Nullable<System.DateTime> BirtdayDate { get; set; }
        public Nullable<int> ID_user { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
    }
}
