//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Reg_Auth.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int ID { get; set; }
        public string Worker_Surname { get; set; }
        public string Worker_Name { get; set; }
        public string Worker_Patronymic { get; set; }
        public Nullable<int> ID_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
